apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: graf
spec:
  ports:
    - port: 3000
  selector:
    app: graf
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-graf-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: graf-deploy
  labels:
    app: graf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: graf
    spec:
      containers:
      - image: pawnikhanna/grafana:v1
        name: graf
        ports:
        - containerPort: 3000
          name: graf
        volumeMounts:
        - name: task-graf
          mountPath: "/usr/share/grafana/data"
      volumes:
        - name: task-graf
          persistentVolumeClaim:
            claimName: task-graf-claim
